--LIGHTWEIGHT
INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Conor McGregor', 33, '22-5', 1, 'LIGHTWEIGHT', 'The Notorious');


INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('ISLAM MAKACHEV', 32, '12-7', 1, 'LIGHTWEIGHT', 'The Eagle');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Justin Gaethje', 33, '22-4', 2, 'LIGHTWEIGHT', 'The Highlight');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Dustin Poirier', 32, '28-6-1', 3, 'LIGHTWEIGHT', 'The Diamond');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Charles Oliveira', 31, '31-8', 4, 'LIGHTWEIGHT', 'Do Bronx');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Beneil Dariush', 32, '21-4-1', 5, 'LIGHTWEIGHT', 'Benny');

--MIDDLEWEIGHT
INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Israel Adesanya', 32, '21-1', 1, 'MIDDLEWEIGHT', 'The Last Stylebender');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Robert Whittaker', 31, '24-5', 2, 'MIDDLEWEIGHT', 'The Reaper');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Paulo Costa', 30, '13-1', 3, 'MIDDLEWEIGHT', 'Borrachinha');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Derek Brunson', 37, '22-7', 4, 'MIDDLEWEIGHT', 'The American Killer');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Darren Till', 28, '18-4-1', 5, 'MIDDLEWEIGHT', 'The Gorilla');


--FEATHERWEIGHT
INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Alexander Volkanovski', 32, '23-1', 1, 'FEATHERWEIGHT', 'The Great');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Max Holloway', 29, '22-6', 2, 'FEATHERWEIGHT', 'Blessed');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Yair Rodriguez', 29, '14-3-2', 3, 'FEATHERWEIGHT', 'El Pantera');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Calvin Kattar', 33, '22-5', 4, 'FEATHERWEIGHT', 'The Boston Finisher');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Korean Zombie', 34, '17-6', 5, 'FEATHERWEIGHT', 'The Korean Zombie');


--HEAVYWEIGHT
INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Francis Ngannou', 34, '16-3', 1, 'HEAVYWEIGHT', 'The Predator');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Ciryl Gane', 31, '9-0', 2, 'HEAVYWEIGHT', 'Bon Gamin');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Derrick Lewis', 36, '25-8-1', 3, 'HEAVYWEIGHT', 'The Black Beast');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Curtis Blaydes', 30, '14-3-1', 4, 'HEAVYWEIGHT', 'Razor');

INSERT INTO FIGHTER(NAME, AGE, RECORD, RANK, DIVISION, NICKNAME)
VALUES ('Alexander Volkov', 33, '34-9', 5, 'HEAVYWEIGHT', 'Drago');




