INSERT INTO FIGHTER(NAME,AGE,RECORD,RANK,DIVISION)
VALUES ('ISLAM MAKACHEV',32,'12-7',1,'LIGHTWEIGHT');

INSERT INTO FIGHTER(NAME,AGE,RECORD,RANK,DIVISION)
VALUES ('Israel Adesanya', 32, '21-1', 1, 'MIDDLEWEIGHT');

INSERT INTO FIGHTER(NAME,AGE,RECORD,RANK,DIVISION)
VALUES ('Alexander Volkanovski', 32, '23-1', 1, 'FEATHERWEIGHT');

INSERT INTO FIGHTER(NAME,AGE,RECORD,RANK,DIVISION)
VALUES ('Francis Ngannou', 34, '16-3', 1, 'HEAVYWEIGHT');

INSERT INTO FIGHTER(NAME,AGE,RECORD,RANK,DIVISION)
VALUES ('Deiveson Figueiredo', 33, '20-1-1', 1, 'FLYWEIGHT');

INSERT INTO FIGHTER(NAME,AGE,RECORD,RANK,DIVISION)
VALUES ('Brandon Moreno', 28, '19-5-2', 2, 'FLYWEIGHT');

INSERT INTO FIGHTER(NAME,AGE,RECORD,RANK,DIVISION)
VALUES ('Askar Askarov', 28, '14-0-1', 3, 'FLYWEIGHT');

INSERT INTO FIGHTER(NAME,AGE,RECORD,RANK,DIVISION)
VALUES ('Max Holloway', 29, '22-6', 2, 'FEATHERWEIGHT');


INSERT INTO FIGHTER(NAME,AGE,RECORD,RANK,DIVISION)
VALUES ('Paulo Costa', 30, '13-1', 3, 'MIDDLEWEIGHT');

INSERT INTO FIGHTER(NAME,AGE,RECORD,RANK,DIVISION)
VALUES ('Robert Whittaker', 31, '24-5', 2, 'MIDDLEWEIGHT');

INSERT INTO U_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_AGE) VALUES ('Linus', 'Nestler','123', 'ln@gmail.com', 3);
INSERT INTO U_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_AGE) VALUES ('Oliver', 'Daxinger', '123', 'od@gmail.com', 5);
INSERT INTO U_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_AGE) VALUES ('Bajtik', 'Berg', '123', 'bb@gmail.com', 5);
INSERT INTO U_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_AGE) VALUES ('Said', 'Nurceski', '123', 'sn@gmail.com', 4);